**Numpy**

1.   NumPy is a general purpose array-processing package.




In [1]:
#import the library
import numpy as np

In [2]:
lst = [1,2,3]

In [4]:
arr = np.array(lst)

In [5]:
type(arr)

numpy.ndarray

In [7]:
lst1 = [1,2,3,4,5]
lst2 = [2,3,4,5,6]
lst3 = [3,4,5,6,7]
arr = np.array([lst1,lst2,lst3])

In [9]:
arr.shape

(3, 5)

In [10]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [11]:
#index

arr[0]

array([1, 2, 3, 4, 5])

In [12]:
arr[0][2]

3

In [13]:
arr[0][2] = 100

In [14]:
arr

array([[  1,   2, 100,   4,   5],
       [  2,   3,   4,   5,   6],
       [  3,   4,   5,   6,   7]])

In [15]:
arr[1:4]

array([[2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [16]:
arr[-1]

array([3, 4, 5, 6, 7])

In [17]:
arr[::]

array([[  1,   2, 100,   4,   5],
       [  2,   3,   4,   5,   6],
       [  3,   4,   5,   6,   7]])

In [18]:
arr[::-2]

array([[  3,   4,   5,   6,   7],
       [  1,   2, 100,   4,   5]])

In [19]:
arr[:,1]

array([2, 3, 4])

In [20]:
arr

array([[  1,   2, 100,   4,   5],
       [  2,   3,   4,   5,   6],
       [  3,   4,   5,   6,   7]])

In [21]:
arr[1:,3:]

array([[5, 6],
       [6, 7]])

In [22]:
arr[:,0:1]

array([[1],
       [2],
       [3]])

In [23]:
arr[:-1,0:1]

array([[1],
       [2]])

In [24]:
arr[:, ::4]

array([[1, 5],
       [2, 6],
       [3, 7]])

In [25]:
## EDA

arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [26]:
arr<2

array([ True, False, False, False, False, False])

In [27]:
arr[arr<2]

array([1])

In [32]:
for i in arr:
  if(i<3):
    print(i)

1
2


In [33]:
arr.shape


(6,)

In [34]:
arr.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [35]:
arr*2

array([ 2,  4,  6,  8, 10, 12])

In [37]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [38]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [40]:
np.random.randint(3,90)

12