**Python Pandas**

In [1]:
import pandas as pd
import numpy as np

In [2]:

np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [5]:
## Create Data Frames

df = pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["Row1","Row2","Row3","Row4","Row5"],columns=["Column1","Column2","Column3","Column4"])

In [6]:
df.head(2)

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7

In [7]:
type(df)

pandas.core.frame.DataFrame

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int64
 1   Column2  5 non-null      int64
 2   Column3  5 non-null      int64
 3   Column4  5 non-null      int64
dtypes: int64(4)
memory usage: 372.0+ bytes


In [9]:
df.describe()


Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [10]:
## Indexing type

#Column Name,row indexing[loc],rowindex number, and column index number[iloc]

In [11]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [12]:
#by using column name
df[['Column1','Column2']]

Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9
Row4       12       13
Row5       16       17

In [13]:
# by using row index name
df.loc['Row3']


Column1     8
Column2     9
Column3    10
Column4    11
Name: Row3, dtype: int64

In [14]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [15]:
df.iloc[2:4,0:2]

Column1  Column2
Row3        8        9
Row4       12       13

In [16]:
df.iloc[2:3,1:]

Column2  Column3  Column4
Row3        9       10       11

In [17]:
df.iloc[0:,::3]

Column1  Column4
Row1        0        3
Row2        4        7
Row3        8       11
Row4       12       15
Row5       16       19

In [5]:
import pandas as pd
import numpy as np

df_new = pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["Row1","Row2","Row3","Row4","Row5"],columns=["Column1","Column2","Column3","Column4"])

In [6]:
 df_new

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [7]:
df_new.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [8]:
## Operations

In [9]:
df_new

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [10]:
df_new.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [13]:
df1 = pd.DataFrame(data=[[1,np.nan,4],[2,3,5],[np.nan,4,7]],index=["Row1","Row2","Row3"],columns=["Column1","Column2","Column3"])

In [14]:
df1

Column1  Column2  Column3
Row1      1.0      NaN        4
Row2      2.0      3.0        5
Row3      NaN      4.0        7

In [15]:
df1.isnull().sum()

Column1    1
Column2    1
Column3    0
dtype: int64

In [17]:
df1.isnull()

Column1  Column2  Column3
Row1    False     True    False
Row2    False    False    False
Row3     True    False    False

In [18]:
df1

Column1  Column2  Column3
Row1      1.0      NaN        4
Row2      2.0      3.0        5
Row3      NaN      4.0        7

In [19]:
df1['Column3'].value_counts()

Column3
4    1
5    1
7    1
Name: count, dtype: int64

In [20]:
df1['Column2'].unique()

array([nan,  3.,  4.])

In [21]:
df1

Column1  Column2  Column3
Row1      1.0      NaN        4
Row2      2.0      3.0        5
Row3      NaN      4.0        7

In [22]:
df1>2

Column1  Column2  Column3
Row1    False    False     True
Row2    False     True     True
Row3    False     True     True

In [25]:
df1[df1['Column1']>0]

Column1  Column2  Column3
Row1      1.0      NaN        4
Row2      2.0      3.0        5